Deployment of the app to Azure
icl-group-09/daedalus pull request #14
Opened 2021-12-02 16:04 UTC by woocashh

2021-12-03 10:23 UTC, egroge requested changes
We shouldn't have the build folder in git
Also, is it possible to have backend code one directory down? Adam had the idea to move it all out again in the pipeline if necessary

2021-12-03 10:29 UTC, TheAdamG requested changes
Move back-end code back to the API folder, make sure deployment only occurs on at least master (would be nice if we could have different deployments to different URL's depending on the branch name), and refactor the app.py back to a files.py to only handle uploading/downloading files to/from the server, not to also serve the front-end

2021-12-03 10:29 UTC, TheAdamG commented on .github/workflows/deployment_daedalusproject.yml
> +      - name: Upload artifact for deployment jobs
Can we make it so this only happens on master? 

Is there anyway we could specify certain branches for deployment and have them deploy to different urls based on the branch name?

2021-12-03 10:29 UTC, TheAdamG commented on app.py
> +
This file was created to only handle serving PCD, image and height map files to/from the front end, hence the flask "files" blueprint. 

Can we move the serving of the index.html to a different file and create a new blueprint for handling the routing for that?

2021-12-21 17:04 UTC, egroge approved these changes

2021-12-21 17:13 UTC, TheAdamG approved these changes

2021-12-21 17:33 UTC, merged